### ISSUE TITLE
当背景色为白色是,状态栏的字看不见

### ISSUE THREAD

**Issue by liunewshine** [Veaer/Glass#2]
状态栏的字不能自动改变颜色吗

**Comment by yemengsky** [comment]
小米5.0 MIUI7 上面也是，当使用白色的背景，通知栏的字体颜色不会修改。

**Comment by Veaer** [comment]
目前只发现在小米和魅族这种机型中可以通过一些特殊的方法更改状态栏颜色，一般机型貌似在 API23之前是没有办法的。。。而这个项目为了适配 API19。。。我不知道有什么解决方法了。。。
